name: Code Quality

on:
  push:
    branches:
      - master
      - develop

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    name: PHP
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.2
          tools: composer:v1
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest
      - name: Reset Winter modules and library
        run: |
          git reset --hard HEAD
          rm -rf ./vendor/wintercms/storm
          wget https://github.com/wintercms/storm/archive/develop.zip -O ./vendor/wintercms/develop.zip
          unzip ./vendor/wintercms/develop.zip -d ./vendor/winter
          mv ./vendor/wintercms/storm-develop ./vendor/wintercms/storm
          composer dump-autoload
      - name: Run code quality checks
        run: ./vendor/bin/phpcs --colors -nq --report="full" --extensions="php" $(git show --name-only --pretty="" --diff-filter=ACMR ${{ github.sha }})
