name: Tests

on:
  push:
    branches:
      - '1.0'
  pull_request:

jobs:
  phpUnitTests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        phpVersions: ['7.1', '7.2', '7.3', '7.4']
      fail-fast: false
    name: PHP ${{ matrix.phpVersions }}
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.phpVersions }}
          extension-csv: mbstring, intl, gd, xml, sqlite
          tools: composer:v1
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest --no-scripts
      - name: Reset Winter modules and library
        run: |
          git reset --hard HEAD
          rm -rf ./vendor/winter/storm
          wget https://github.com/wintercms/storm/archive/1.0.zip -O ./vendor/winter/1.0.zip
          unzip ./vendor/winter/1.0.zip -d ./vendor/winter
          mv ./vendor/winter/storm-1.0 ./vendor/winter/storm
          composer dump-autoload
      - name: Run post-update Composer scripts
        run: |
          php artisan winter:util set build
          php artisan package:discover
      - name: Run Linting and Tests
        run: |
          ./vendor/bin/parallel-lint --exclude vendor --exclude storage --exclude tests/fixtures/plugins/testvendor/goto/Plugin.php .
          ./vendor/bin/phpunit
